dist: xenial
language: java
jdk:
- oraclejdk9

before_install:
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"
install: mvn install -DskipTests -Dgpg.skip
script: mvn -B verify
